### ISSUE TITLE
Allow users to disable external linters

### ISSUE THREAD

**Issue by orokanasaru** [DeepCodeAI/vscode-extension#10]
I use a heavily customized tslint.json file that extends from multiple npm packages.
According to the documentation, DeepCode falls back to a default tslint configuration in this situation.
This leads to DeepCode having problems with literally every statement in my repos, since one of the customizations I have is that I don't use semicolons.

I already run linters as I type in VS Code, as a commit hook, and in CI, so DeepCode running them with a different config is just adding negative value.

Please let users disable external linters.

**Comment by deepcodeg** [comment]
Hi @orokanasaru, sounds like a good idea, thanks. 

I don't have a workaround at the moment and it seems like an issue - sorry about that. I would think about how to incorporate it into our roadmap 👍

**Comment by Arvi3d** [comment]
Hi @orokanasaru We've just made a major release, that should have fixed this issue. We don't enable linters by default now.
