### ISSUE TITLE
CRITICAL - Extension ignores all .gitignore / .dcignore - uploaded everything

### ISSUE THREAD

**Issue by alystair** [DeepCodeAI/vscode-extension#78]
It uploaded over 5k files, node_modules etc...  getting tons of errors for things outside the scope of the project. How do I force deletion of items uploaded to your server? This is also a major privacy/code licensing issue.

**Comment by alystair** [comment]
.gitignore contents
```
# Secrets and settings
/cache/*
/favicon.ico
cache_*
env.php
robots.txt
secrets.php

# Common directories
/node_modules/
/vendor/
composer.lock
package-lock.json

# Best practice
.env

# Numerous always-ignore extensions
*.diff
*.err
*.log
*.orig
*.rej
*.swo
*.swp
*.vi
*~

# OS & Editor folders
.cache
.DS_Store
.eslintrc.js
.idea
.project
.rnd
.settings
.vscode
gulpfile.js
nbproject
thumbs.db
```

your extension generated a .dcignore file, which hasn't been modified.

For reference this project is opened within a workspace

**Comment by michelkaporin** [comment]
@alystair I know it's an old issue but wanted to let you know that this has been fixed in the latest version of [Snyk extension](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner).
