### ISSUE TITLE
Ability to Ignore or Skip Certain Files

### ISSUE THREAD

**Issue by jacobgqc** [DeepCodeAI/vscode-extension#8]
Hello,

This seems like a very useful tool, but I was wondering if there's a way to configure the extension so it will ignore (or skip) certain files?
My web application, for example, contains various third-party Javascript files (i.e. JQuery and Bootstrap). Files such as these end up flooding the VSCode Problems window when I run DeepCode.

Thanks for any help,
Jacob

**Comment by deepcodeg** [comment]
Hi @jacobgqc and @yGuy, thanks for looking into this, happy to say we are working on this in our current sprint. There will be a new `.dcignore` file (similar to `.gitignore`). The files matching the patterns in `.dcignore` will not be uploaded to our servers. I hope we could get it in a few weeks :)

**Comment by Arvi3d** [comment]
Hi @jacobgqc and @yGuy, I'm happy to announce this feature is live now. Please add .gitignore file to any folder of your project, and our Extension will apply your rules.

**Comment by Drumstix42** [comment]
@Arvi3d With or without a `.dcignore` file I've still been having troubles with DeepCode scanning the entirety of the  `node_modules` folder. I've been seeing this issue for several versions now, so I think it's still a bug.

I've tried setting the file and restarting VSCode. I've try uninstalling and re-installing the extension. Not sure where to go from here. Always takes quite a long time to scan because of this:

![image](https://user-images.githubusercontent.com/2993354/101570148-d02d1500-39a3-11eb-9e60-e0b5439029a4.png)

**Comment by yGuy** [comment]
Have you tried using `.gitignore` like he said in his last comment?

**Comment by Arvi3d** [comment]
@Drumstix42 could you please share content of your files:
 - .gitignore
 - .dcignore

to check their format

**Comment by Drumstix42** [comment]
> 
> 
> @Drumstix42 could you please share content of your files:
> 
>     * .gitignore
> 
>     * .dcignore
> 
> 
> to check their format

@Arvi3d 

.gitignore:
```
dist/
bower_components
node_modules
coverage
eslint-report.json
.dccache
.DS_Store
.eslintcache
.sass-cache
.scannerwork
.tmp/
.idea
.vscode/**/*
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
.env.local
.env.*.local
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.idea
!.vscode/settings.json
```

.dcignore
```
node_modules
```
```

**Comment by Arvi3d** [comment]
thank you. You don't really need .dcignore, as you have node_modules in .gitignore.
Anyway, it's not clear to me why it's not working for you. Would you be able to connect via Zoom? I'd send you an invitation via Github, but I need your confirmation first.

**Comment by Drumstix42** [comment]
> 
> 
> thank you. You don't really need .dcignore, as you have node_modules in .gitignore.
> Anyway, it's not clear to me why it's not working for you. Would you be able to connect via Zoom? I'd send you an invitation via Github, but I need your confirmation first.

Yes I'd be open to that. I'm in USA, timezone EST. Send me a message and we can find a time.
