### ISSUE TITLE
Issues pushing button "Connecting VS Code with Snyk and analyse" inside a WSL2 container

### ISSUE THREAD

**Issue by fbuenafuente** [DeepCodeAI/vscode-extension#89]
Opening code directly on host system, there is no problem: connection is sucessful and code is analized.
But trying to use extension inside WSL2 container and push the button to connect (image attached), when trying to connect to Snyk does not work. This only happens with Snyk version, not with DeepCode deprecated version. Using DeepCode version authenticates but doesn't analyze files and not prints logs related to the extension.

![imagen](https://user-images.githubusercontent.com/35167509/126878808-1b69da55-9d60-4a69-b693-709fd152f4de.png)

Logs on VS Code prints on renderer1.log the error:
`[renderer1] [error] command 'snyk.login' not found: Error: command 'snyk.login' not found
    at g._tryExecuteCommand (vscode-file://vscode-app/d:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:3360)
    at vscode-file://vscode-app/d:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:3241
    at async u.open (vscode-file://vscode-app/d:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:628:19110)
    at async n.open (vscode-file://vscode-app/d:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:628:21008)
`

**Comment by michelkaporin** [comment]
@fbuenafuente thank you for raising the issue with us. We have fixed this bug in the [latest](https://github.com/snyk/vscode-extension/releases/tag/v1.1.0) release of the extension. Could you please check it again and let us know if it works now?

**Comment by fbuenafuente** [comment]
Hi @michelkaporin , we have checked the latest version 
![imagen](https://user-images.githubusercontent.com/35167509/130119431-8930f403-2051-4a81-8631-4662ea780971.png)
in two different environments, WSL and Docker Dev container. 

I'll close this issue as I can confirm that is fixed and works fine. Thank you for your help!!
