### ISSUE TITLE
Typescript - Class property must be marked either 'private', 'public', or 'protected'

### ISSUE THREAD

**Issue by SeanSobey** [DeepCodeAI/vscode-extension#9]
I got this warning on the `public` modifier for a class method.

**Comment by deepcodeg** [comment]
@SeanSobey thanks for reporting it - it should be fixed, I agree 😄. Could you point me to the exact location

**Comment by SeanSobey** [comment]
Yeah sure, it was [this one](https://github.com/SeanSobey/ChartjsNodeCanvas).

**Comment by deepcodeg** [comment]
Thanks for shooting back, unfortunately I didn't see such an issue in the [analysis](https://www.deepcode.ai/app/gh/SeanSobey/ChartjsNodeCanvas/a8606be69d72e41d8efb2ccba68c86a673b7df3a/_/dashboard/). Nevertheless I will be on the lookout for such an issue!

**Comment by SeanSobey** [comment]
Yes I enabled and ran in vscode again now and seems to be resolved. Thanks for looking into it, I will reopen if I see it again.
